### ISSUE TITLE
/showitem gives unhandled exception occurred.

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#278] opened 2022-05-31 21:04 UTC
**Issue**
Using /showitem gives this error:
![image](https://user-images.githubusercontent.com/48634310/171283635-537c7bdc-6b54-40f9-9123-287d3d86880a.png)

Although it seems to work some of the time?

Unsure of project.
**Ticket refence number:**
RTS-
102212
![image](https://user-images.githubusercontent.com/48634310/171283775-0209990b-f0dc-4a5d-9c0b-0ef3050bd054.png)

102237
![image](https://user-images.githubusercontent.com/48634310/171283810-52c057bf-655b-4612-ba02-6f488964c558.png)

102243
![image](https://user-images.githubusercontent.com/48634310/171283860-1d859b31-85d3-46e6-83f9-eac2ebfc9bcb.png)

**Comment by Kowaman** [comment] 2022-06-01 04:23
Duplicate of #267

**Closed by Kowaman** 2022-06-01 04:23 UTC
Labels: bug, confirmed
