### ISSUE TITLE
Stack of crafted whistles disappearing af

### ISSUE THREAD

**Issue by chenn04** [Lord-of-the-Craft/tracker#227] opened 2022-01-14 01:03 UTC
**Issue**
After crafting 4 whistles, a player used it to capture a horse, after which it took 3 of the whistles and left one.

**Ticket refence number:**
RTS-88310

**Comment by FallenVibe** [comment] 2022-01-15 21:39
Duplicate of #200

**Closed by FallenVibe** 2022-01-15 21:39 UTC
