### ISSUE TITLE
Equipping a two-handed weapon while holding an item in your offhand will delete the extra item

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#186] opened 2021-08-21 20:52 UTC
**Issue**
If you're holding an item in your offhand (item doesn't seem to matter), and you equip a two-handed melee weapon, the item being held in the offhand disappears. 

**Ticket refence number:**
RTS- 73680

**Comment by FallenVibe** [comment] 2021-09-22 11:56
Duplicate of #191 , closing this for cleanup.

**Closed by FallenVibe** 2021-09-22 11:56 UTC
Labels: bug, confirmed
