### ISSUE TITLE
LC item bypass (creative to survival inventory)

### ISSUE THREAD

**Issue by ghost** [Lord-of-the-Craft/tracker#264] opened 2022-05-11 03:15 UTC
**Issue**
1. Launch limited creative with persona A
2. Place any desired item in your inventory (A)
3. Switch persona B through the /menu GUI
4. Get out of limited creative (usually will wipe the current survival inventory of persona B)
5. Switch back to persona A
6. Items previously placed in persona A's inventory will now be available as survival inventory

**Ticket refence number:**
RTS-100471

**Comment by FallenVibe** [comment] 2022-05-11 22:31
Duplicate of #208

**Comment by Kowaman** [comment] 2022-06-01 05:29
> 

Unrelated to the regular persona swap dupe, although they work on basically the same mechanism they do not have the same cause. That is random and due to ArcheCore, this is relocatable and caused directly by LC.

**Comment by Kowaman** [comment] 2022-06-01 05:35
Duplicate of https://github.com/Lord-of-the-Craft/tracker/issues/208

**Comment by Kowagirl** [comment] 2024-08-07 04:26
Fixed a while ago

**Closed by Kowagirl** 2024-08-07 04:26 UTC
Labels: bug, confirmed
