### ISSUE TITLE
Breeding Animal Energy Bug

### ISSUE THREAD

**Issue by MCVDK** [Lord-of-the-Craft/tracker#72] opened 2021-01-03 08:50 UTC
Logging out after breeding animals let's you dodge the vortex energy drain. (Submitted by DiscoLiquid)

See RTS-54154

**Comment by Deer2underscores** [comment] 2021-01-13 05:41
I couldn't replicate it on the dev server but I think it may work if you have someone else around to keep the chunk loaded in while the animals do their thing.

**Comment by Kowaman** [comment] 2021-02-02 23:27
Duplicate of #59

**Closed by Kowaman** 2021-02-02 23:27 UTC
Labels: bug, can not replicate, needs testing
