### ISSUE TITLE
Herbs nodes not visible 

### ISSUE THREAD

**Issue by DesiredBreakfast** [Lord-of-the-Craft/tracker#70] opened 2021-01-03 05:27 UTC
**Minecraft Username**
Kholibrii

**Describe the bug**
The item that floats above the blocks to indicate where an ST herb does not seem to appear when they are harvestable.(Similar to the issue that occurred with the Cotton). You are still able to harvest the herb if it is off CD, but you can not see the item indicator. 

**How did this occur**
I went around harvesting nodes and found a herb that had the indicator floating above it, then found more spots that were decorated in an identical fashion and found where the nodes were placed. I was able to harvest them despite the item indicator not being present.
**EDIT: This appears to not happen every time, it's just happening periodically and others have had this issue**
**Expected behavior**
A harvestable herb node within the plugin should have an Item floating above it to indicate that there is a herb there, along with the name of the herb above it. When harvested the item would disappear till it was off the cooldown once more.

**Screenshots**
![image](https://user-images.githubusercontent.com/74981182/103472227-c69f8e80-4d50-11eb-8f00-7125f623b33d.png)
(This is what I mean by item indicator)

**Minecraft version:**
I was originally on 1.16.4, but then moved to 1.15.2 and the bug was presistant.

**Additional context**
There also seems to be an additional bug where the Item Indicator does not appear on the block you have to left-click to harvest it. The indicator seems to have moved 1 to 2 blocks from where it should be.

**Comment by Deer2underscores** [comment] 2021-01-07 21:44
Only appears to happen occasionally, unsure of the cause but its been reported by several players.

**Comment by Kowaman** [comment] 2021-01-25 05:03
Fixed by https://github.com/Lord-of-the-Craft/lotc-master-vortex/commit/3f90da375a17819112d65b0961535f9ef080a3a2

**Closed by Kowaman** 2021-01-25 05:03 UTC
Labels: bug, confirmed
